In [1]:
import json

In [2]:
file = open(r"data\uit-course.json", encoding='utf-8')
data = json.load(file)

In [3]:
data["test"][90]

{'id': 'UIT_3103',
 'context': 'Môn Quản trị chuỗi cung ứng (mã môn MKTG4223) trình bày kiến thức toàn diện về quản trị Logistics, nền tảng của quản trị chuỗi cung ứng. Trong đó, hệ thống ERP đóng vai trò hỗ trợ các hoạt động lập kế hoạch, tổ chức, thực hiện và kiểm tra chuỗi cung ứng hiệu quả trong các tổ chức doanh nghiệp hiện đại.',
 'question': 'Hệ thống nào hỗ trợ các hoạt động lập kế hoạch trong quản trị chuỗi cung ứng?',
 'answer': {'text': ['hệ thống ERP'], 'answer_start': [147]}}

In [10]:
idx = 3384
for text in data["validation"]:
    f = open(rf"C:\Users\leduc\OneDrive\Desktop\NLP\UIT-chatbot\RAG_data\text_{idx}.txt", "w", encoding='utf-8')
    f.write(text["context"])
    f.close()
    idx+=1

In [ ]:
df = []

In [14]:

for text in data["test"]:
    # print(text["context"])
    df.append({"context": text["context"]})

Môn Ngôn ngữ lập trình C# (mã môn CS511) giúp sinh viên:
- Hiểu rõ ngôn ngữ lập trình C#
- Nắm vững kiến trúc .NET
- Nắm được cách lập trình trên môi trường Windows
- Có khả năng lập trình giao diện
- Lập trình đồ họa GDI+
- Xử lý tập tin và thư mục
- Kết nối cơ sở dữ liệu
- Lập trình đa luồng
- Xây dựng ứng dụng trên nền .NET Framework
Đối tượng môn học Phân tích thiết kế hệ thống truyền thông và mạng với mã môn học là NT201, tóm tắt nội dung cơ bản như sau: Chương trình học được phân định theo hai phần chính:

- Phần một, mở đầu từ chương 1 đến chương 6, làm sáng tỏ về phân tích hệ thống gồm các khái niệm cốt lõi, cấu trúc hệ thống, nhiệm vụ của hệ thống, các bước phát triển và trạng thái hoạt động của hệ thống.

- Phần hai, bao hàm từ chương 7 đến chương 12, chuyên sâu về thiết kế và triển khai hệ thống, bao gồm: lộ trình phát triển hệ thống, thông số kỹ thuật của hệ thống, những vấn đề nảy sinh trong quá trình thực hiện, phân tích các hỗ trợ phục vụ cho ra quyết định, thủ tục kiểm tra và xác nhận.
Môn học CS406 là môn học về Xử lý ảnh và ứng dụng. Nội dung môn học tập trung vào việc cung cấp kiến thức cơ bản về xử lý ảnh và kỹ thuật xây dựng hệ thống thông tin dựa trên ảnh cho sinh viên.
Môn Phân tích thiết kế hệ thống (MSIS3303) cung cấp một loạt các khái niệm, phương pháp và ứng dụng để tối ưu hóa quy trình kinh doanh, thúc đẩy sự phát triển vượt trội trên thị trường cạnh tranh. Khóa học khám phá tác động của tự động hóa vào các quy trình được thiết kế mới để gia tăng lợi thế cạnh tranh cho doanh nghiệp. Các nghiên cứu điển hình từ các công ty hàng đầu minh họa cách sắp xếp hợp lý quy trình làm giảm đáng kể chi phí hoạt động, nâng cao hiệu suất và mang lại lợi ích cho tất cả các bên liên quan.
Môn học có tên là CS405 và nó liên quan đến Logic mờ và ứng dụng. Tóm tắt nội dung của môn học như sau: Lý thuyết mờ là một công cụ quan trọng trong việc giải quyết các vấn đề liên quan đến tính toán mềm trong lĩnh vực Khoa học Máy tính và các ngành kỹ thuật khác. Môn học này có 2 mục tiêu chính: trang bị kiến thức cơ bản về Lý thuyết mờ và áp dụng lý thuyết mờ vào một số ứng dụng.
Môn học Nhập môn ẩn thông tin và ứng dụng được ký hiệu là IE406. Nội dung của môn học tập trung vào lĩnh vực nghiên cứu ẩn thông tin để giải quyết hiệu quả các vấn đề liên quan đến an toàn thông tin trên dữ liệu số hóa, đặc biệt là trong bối cảnh an toàn và bảo mật đang trở nên cấp thiết tại Việt Nam và thế giới. Học phần cung cấp kiến thức cơ bản về ẩn thông tin, bao gồm các phương pháp nhúng và trích xuất thông tin, kỹ thuật phân tích và phát hiện thông tin, ứng dụng thực tế của ẩn thông tin trong bảo vệ bản quyền, xác thực nội dung, dò tìm, giám sát, kiểm soát sao chép, v.v. Qua đó, môn học cũng giới thiệu định hướng nghiên cứu và ứng dụng ẩn thông tin trong tương lai.
Phần học Khoa học phương pháp quản lý có mã khóa học là MSIS3233. Tóm tắt nội dung khóa học: Khóa học này đề cập đến việc đưa ra quyết định trong bối cảnh quản lý, kết hợp một số phương án tiếp cận có hệ thống để đưa ra quyết định trong những vấn đề mà các nhà quản lý thường gặp. Trong thế giới hiện đại, sự mách bảo khi ra quyết định có thể dẫn ta đến những chỉ dẫn không an toàn. Điểm nổi bật của khoa học quản lý là xây dựng một mô hình cụ thể, đơn giản hóa các khía cạnh liên quan của tiến trình ra quyết định, các mô hình như vậy thường dựa trên các phương pháp toán học định lượng.
Môn An toàn mạng máy tính có mã NT101, chuyên sâu vào các chủ đề sau:

- Những nguyên tắc cơ bản về bảo mật mạng máy tính
- Thiết lập một tổ chức an toàn, quản lý quyền truy cập và kiểm soát truy cập
- Các biện pháp ngăn chặn tấn công hệ thống, bảo vệ khỏi các cuộc tấn công botnet
- Các vấn đề bảo mật mạng liên quan đến phần mềm độc hại
- Bảo mật mạng Windows và Unix/Linux
- Bảo mật mạng truyền dẫn, LAN, mạng không dây và mạng di động
Môn IT008 có tên đầy đủ là Lập trình trực quan, cung cấp kiến thức và kỹ thuật lập trình bằng giao diện trực quan trên hệ điều hành Windows. Nội dung học tập bao gồm những phương pháp và quy trình tạo ứng dụng Windows, xử lý tin nhắn, sử dụng giao diện điều khiển, quản lý bộ nhớ, liên kết thư viện động và lập trình đa nhiệm.
Môn phần Phát triển Phần mềm Mã nguồn mở (mã môn SE301) cung cấp những kiến thức tổng quan về sự phát triển của phần mềm mã nguồn mở, các khái niệm bản quyền có liên quan. Môn học này cũng trình bày các phương pháp xây dựng phần mềm mã nguồn mở và đào tạo sử dụng SVN để xây dựng loại phần mềm này.
NT310 - Môn học Pháp chứng mạng di động chuyên sâu trong các kỹ thuật pháp chứng di động cơ bản, cung cấp tổng quan về các loại pháp chứng di động, công nghệ cần dùng, bằng chứng điện tử và phương thức thu thập. Môn học trang bị cho sinh viên phương pháp tiếp cận hệ thống trong quá trình điều tra pháp chứng di động (bao gồm cả điều tra tư pháp và điều tra trong doanh nghiệp), đồng thời hướng dẫn về yêu cầu của phòng thí nghiệm pháp chứng di động, bao gồm cả phần cứng, phần mềm và thiết bị phục hồi dữ liệu cần thiết để thực hiện công tác pháp chứng số trong phòng thí nghiệm. Thông qua lý thuyết và thực hành, sinh viên sẽ có khả năng thu thập chứng cứ từ điện thoại di động và hiện trường bằng cách sử dụng các công cụ thu thập dữ liệu.
Môn học Công nghệ thoại IP có mã môn học là NT303. Tóm tắt nội dung môn học như sau: Nội dung môn học bao gồm tổng quan về xu thế phát triển của Internet và công nghệ thoại IP, các giao thức báo hiệu và xử lý cuộc gọi. Môn học cũng đề cập đến các kỹ thuật nén tín hiệu thoại bao gồm nguyên lý chung đến các chuẩn nén. Các cách thức ghi địa chỉ, đánh số, phương pháp định tuyến giữa mạng điện thoại truyền thống (PSTN) với mạng điện thoại IP và các vấn đề đo kiểm chất lượng dịch vụ thoại IP, các thiết bị, phần mềm đầu cuối và triển khai mạng điện thoại IP. Môn học cũng đề cập các công nghệ VoIP của Cisco và mã nguồn mở Asterisk trong đó trình bầy chuyên sâu về lập trình một mạng thoại với nguồn mở Asterisk.
Môn Sofware Quality Management có mã hiệu là MSIS3242. Tóm tắt nội dung môn học bao gồm: tìm hiểu quy trình tạo ra các hệ thống phần mềm phức tạp, từ thiết kế, phát triển, bảo trì tới kiểm thử; các chuẩn mực phục vụ mục đích giảm thiểu chi phí, tăng độ tin cậy, cũng như khả năng đổi mới của hệ thống phần mềm. Môn học cung cấp nền tảng lý thuyết và thực hành các công cụ đảm bảo, đo lường chất lượng phần mềm, tập trung vào những chủ đề như: đảm bảo chất lượng, ngăn ngừa và khắc phục lỗi, kỹ thuật kiểm định, giám sát, các chỉ định và phương pháp xác minh, các giải pháp cải tiến chất lượng phần mềm.
Khóa học An toàn mạng không dây và di động (mã môn NT330) trình bày những khái niệm cơ bản về đánh giá và bảo mật, cũng như giải quyết các vấn đề liên quan. Khóa học tập trung vào các giải pháp bảo vệ công nghệ không dây và thiết bị di động như Bluetooth, WiFi, WiMax, 2G và 3G. Ngoài ra, khóa học sẽ thảo luận về các kỹ thuật bảo mật trong các ứng dụng tải xuống trên thiết bị di động thông qua hệ thống mạng di động. Cuối cùng, khóa học sẽ đề cập đến các vấn đề bảo mật và các giải pháp an toàn cho các công nghệ không dây và di động tiên tiến như mạng cảm biến, di động 4G và mạng IMS.
Môn Thực tập doanh nghiệp mang mã NT115, bao gồm chương trình thực tập cuối khóa tại các doanh nghiệp, cơ quan sự nghiệp trong lĩnh vực liên quan. Mục tiêu là cho sinh viên cơ hội trải nghiệm môi trường nghề nghiệp thực tế, làm quen với các công việc và tích lũy kinh nghiệm. Trong quá trình thực tập, sinh viên sẽ học hỏi từ các chuyên gia, trực tiếp xử lý các tình huống phát sinh trong phạm vi chuyên môn mà họ đã lựa chọn.
Môn học Dịch máy có mã môn học là CS325. Tóm tắt nội dung môn học như sau: Dịch máy là một lĩnh vực trong ngôn ngữ học máy tính, nghiên cứu về phần mềm máy tính dùng để dịch văn bản hoặc tiếng nói từ một ngôn ngữ tự nhiên sang một ngôn ngữ khác. Ở mức độ căn bản, MT chỉ đơn giản là thay thế các từ trong một ngôn ngữ tự nhiên bằng các từ thuộc ngôn ngữ khác. Với kỹ thuật ngữ liệu, chúng ta có thể dịch được những văn bản phức tạp hơn, cho phép xử lý tốt hơn với các loại hình ngôn ngữ khác nhau, nhận dạng cụm từ và thành ngữ.
Môn Lập trình hệ thống (mã môn: NT209) là môn học trang bị cho sinh viên những nền tảng kiến thức về nguyên lý lập trình hệ thống máy tính, bao gồm ngôn ngữ Assembly cơ bản, cách chuyển đổi giữa ngôn ngữ cấp cao và mã máy. Không chỉ dừng lại ở đó, môn học còn cung cấp các kỹ năng tối ưu hóa chương trình, hiểu biết về stack, pointer, cache và kiến trúc máy tính để tạo ra các phần mềm an toàn, hiệu quả và có tầm nhìn tổng quan. Ngoài ra, kiến thức của môn học này còn hữu ích trong các kỹ thuật dịch ngược, gỡ lỗi và kiểm tra lỗi phần mềm.
Môn Nhập môn lập trình thi đấu (IT011) là môn học chuyên biệt dành cho sinh viên đã có nền tảng lập trình cơ bản và đã tham dự các cuộc thi lập trình. Môn học này trang bị cho sinh viên những kiến thức, kỹ năng và thái độ thiết yếu để đối mặt với các bài toán trong các cuộc thi lập trình quốc gia và quốc tế. Sinh viên sẽ được hướng dẫn cách ứng dụng các kỹ thuật lập trình và cấu trúc dữ liệu để giải quyết các thử thách tính toán hiệu quả. Các thuật toán điển hình được giới thiệu bao gồm vét cạn, chia để trị, tham lam, qui hoạch động,... Ngoài ra, sinh viên còn được hướng dẫn cách sử dụng các thư viện lập trình (C/C++, Java, Python,...) để thực hiện bài toán trên máy tính.
Môn Các hệ thống mô phỏng trên máy tính được mã hóa thành MSIS4443. Nói một cách cô đọng, môn học này tập trung vào việc mô phỏng các hệ thống dựa trên các sự kiện cụ thể. Các hệ thống thường được đưa vào mô phỏng bao gồm hệ thống lưu trữ, hệ thống quản lý tài chính, hệ thống giao tiếp dữ liệu, các bài toán về hệ thống thông tin hoặc tình trạng xếp hàng. Sinh viên cần thu thập và ước lượng dữ liệu liên quan, từ đó nhận ra việc mô phỏng là một công cụ hữu ích trong cả khoa học quản lý lẫn các hệ thống thông tin.
Bộ môn Tính toán song song & phân tán được xác định bằng mã DS104. Về nội dung học tập, bộ môn cung cấp cái nhìn tổng thể về hệ thống tính toán song song và tính toán phân tán, bao gồm các khái niệm, mô hình và những thách thức liên quan. Bộ môn tập trung vào các phương pháp và nền tảng cụ thể để giải quyết các vấn đề dữ liệu lớn trong bối cảnh tính toán song song và phân tán.
Môn học Chuyên đề E-Learning, được mã hóa là SE350, mang đến cho sinh viên cái nhìn toàn diện về lĩnh vực học tập trực tuyến. Môn học trình bày các khái niệm cơ bản của E-Learning, bao gồm mô hình và công cụ sử dụng trong lĩnh vực này. Sinh viên sẽ được hướng dẫn thiết kế và triển khai các hệ thống E-Learning hiệu quả. Ngoài ra, vấn đề bản quyền trí tuệ cũng được đề cập trong nội dung môn học.
Cử nhân ngành Kỹ thuật Máy tính (Áp dụng từ khóa 18 - 2023) Hình thức đào tạo: Chính quy tập trung.- Số tín chỉ đào tạo: 128 tín chỉ. - Thời gian đào tạo: 4 năm (8 học kỳ)
Môn Quản trị chuỗi cung ứng (mã môn MKTG4223) trình bày kiến thức toàn diện về quản trị Logistics, nền tảng của quản trị chuỗi cung ứng. Trong đó, hệ thống ERP đóng vai trò hỗ trợ các hoạt động lập kế hoạch, tổ chức, thực hiện và kiểm tra chuỗi cung ứng hiệu quả trong các tổ chức doanh nghiệp hiện đại.
Cử nhân ngành Trí tuệ Nhân tạo (Áp dụng từ khóa 18 - 2023)  Mục tiêu chung: Chương trình đào tạo ngành Trí tuệ nhân tạo hướng đến mục tiêu đào tạo nguồn nhân lực chất lượng cao đạt trình độ khu vực và quốc tế về Trí tuệ nhân tạo. Chương trình trang bị cho người học nền tảng kiến thức vững vàng kết hợp cùng kiến thức chuyên sâu cập nhật, hiện đại về Trí tuệ nhân tạo. Người học hiểu và có khả năng làm chủ, vận dụng sáng tạo các thành tựu tiên tiến của ngành; có kỹ năng cần thiết và thái độ chuẩn mực trong phát triển nghề nghiệp.
Môn Giải tích, có mã môn là MA006, là môn học thuộc chương trình đại cương, bắt buộc với toàn thể sinh viên. Nội dung môn học này bao gồm các kiến thức cơ bản về phép tính vi phân hàm số nhiều biến; phép tính tích phân (tích phân bội), tích phân đường, tích phân mặt; kỹ năng khảo sát chuỗi số, chuỗi hàm, tích phân suy rộng; nhận dạng và giải các phương trình vi phân cấp một, cấp cao, v.v. Từ đó, sinh viên được trang bị kiến thức nền tảng để tiếp tục học các môn chuyên ngành hoặc phục vụ cho quá trình thực hiện khóa luận tốt nghiệp.
Môn học có tên gọi là CS338 và nó thuộc lĩnh vực Nhận dạng. Nội dung của môn học này bao gồm kiến thức cơ bản về các thuật toán nhận dạng có tham số và phi tham số như SVM, Mạng Neural Network, Mô Hình Markov Ẩn, Maximum Likelihood, K-Nearest Neighbor, K-Mean. Sinh viên có thể áp dụng các thuật toán này vào bài toán nhận dạng với dữ liệu đặc trưng được rút trích từ các dữ liệu thực tế.
Môn học CE407 - Đồ án chuyên ngành Hệ thống nhúng và Robot dành cho sinh viên học chuyên đề tốt nghiệp. Đồ án này giúp sinh viên phát triển kỹ năng thiết kế hệ thống nhúng và robot. Sau khi hoàn thành môn học, sinh viên sẽ có kiến thức tổng hợp về chuyên ngành hệ thống nhúng và robot, kỹ năng tìm hiểu, nghiên cứu và giải quyết bài toán trong lĩnh vực hệ thống nhúng, kỹ thuật máy tính, cũng như kỹ năng thuyết trình, giao tiếp và làm việc nhóm. Môn học cũng khuyến khích thái độ làm việc tích cực trong lĩnh vực hệ thống nhúng.
Môn học NT212 cung cấp tổng quan về lý thuyết An toàn dữ liệu và Khôi phục thông tin sau sự cố, bao gồm các chủ đề cốt lõi sau:

- Quy trình, phương pháp lập kế hoạch ứng phó sự cố cấp doanh nghiệp và các nguyên tắc xử lý.
- Các kỹ thuật khắc phục sự cố, đánh giá mức độ thiệt hại và bảo vệ dữ liệu quan trọng.
- Nguyên tắc triển khai kế hoạch khắc phục sự cố, kiểm tra liên quan, quản lý thông tin trong quá trình khôi phục và đánh giá hiệu quả khôi phục.

Đối với chương trình cử nhân tài năng, nội dung học tập sẽ sâu hơn, bao gồm:

- Đánh giá rủi ro do sự cố liên quan đến dữ liệu đối với hoạt động của tổ chức, các biện pháp phòng ngừa và phục hồi.
- Các bài tập thực hành nâng cao về kỹ thuật sao lưu dữ liệu, công cụ phục hồi và thiết lập quy trình quản lý dữ liệu tối ưu hóa rủi ro.
- Sinh viên sẽ hoàn thành một dự án nghiên cứu chuyên sâu, tự nghiên cứu tài liệu và trình bày kết quả theo yêu cầu của giảng viên.
Cử nhân ngành Thương mại điện tử (Áp dụng từ Khoá 18 - 2023) Đào tạo nguồn nhân lực có kiến thức và kỹ năng chuyên sâu về Thương mại điện tử nhằm giải quyết các bài toán về kinh doanh - quản lý hiện nay, nghiên cứu và chuyển giao công nghệ tiên tiến trong CNTT vào thương mại điện tử, đặc biệt là hướng vào các ứng dụng nhằm góp phần đẩy mạnh sự nghiệp công nghiệp hóa, hiện đại hóa đất nước.
Môn học CS3613 là môn học Cơ sở tính toán. Nội dung môn học được tóm tắt như sau: Giới thiệu lý thuyết cổ điển về khoa học máy tính, ứng dụng các máy tuần tự vào các thiết bị, tiến trình và lập trình. Các mô hình tính toán bao gồm automat hữu hạn, automat đẩy xuống và máy Turing. Ngoài ra, môn học còn trình bày về vai trò của không tất định và giới hạn của máy tính số, cũng như khái niệm giải được và không giải được.
Môn học CS217 là môn học về hệ cơ sở tri thức và hệ chuyên gia, phương pháp thiết kế và các ứng dụng. Nội dung chính bao gồm: khái niệm, cấu trúc và quy trình xây dựng hệ thống; phương pháp thiết kế các thành phần trung tâm của hệ thống như cơ sở tri thức và bộ suy diễn cùng các kỹ thuật liên quan khác; thiết kế và xây dựng các ứng dụng cụ thể.
Môn học Công nghệ .NET mang mã lớp SE310, bao gồm các kiến thức cốt lõi: kiến trúc, nền tảng công nghệ .Net; kỹ năng và phương pháp lập trình hướng đối tượng trong .Net; tích hợp công nghệ (C#) và hệ quản trị CSDL để xây dựng hệ thống quản lý. Ngoài ra, học phần còn cung cấp hướng tiếp cận chuyên sâu trong phát triển ứng dụng với công nghệ .Net.
Chủ đề Lập trình hướng đối tượng, mã môn học MSIS2433, bao gồm:

- Tổng quan về lập trình hướng đối tượng, tập trung vào nguyên tắc thiết kế có cấu trúc, phát triển và kiểm thử.
- Cú pháp ngôn ngữ lập trình, vai trò của mô hình hướng đối tượng trong thiết kế và triển khai ứng dụng phần mềm.
- Nguyên lý trao đổi dữ liệu và các chủ đề liên quan.
- Lập trình hướng đối tượng nhấn mạnh vào tính đóng gói (tạo lớp và thể hiện), tính kế thừa (xác định lớp kế thừa và phương thức từ lớp hiện có) và tính đa hình.
Môn học Khóa luận tốt nghiệp có mã là SE505. Về nội dung học phần, để tốt nghiệp, sinh viên có hai lựa chọn: hoàn thành khóa luận tốt nghiệp hoặc thi 3 học phần chuyên đề tốt nghiệp. Với lựa chọn khóa luận tốt nghiệp, sinh viên sẽ tiến hành nghiên cứu và xây dựng phần mềm trong các chuyên ngành gồm kỹ thuật phần mềm, lập trình nhúng hoặc lập trình game dưới sự hướng dẫn của giảng viên. Cuối cùng, sinh viên cần bảo vệ thành công khóa luận trước hội đồng chấm thi. Trong khi đó, với lựa chọn 3 học phần chuyên đề, sinh viên sẽ học và thi 3 học phần do khoa quy định.
Đối tượng môn học Phân tích thiết kế hệ thống truyền thông và mạng với mã môn học là NT201, tóm tắt nội dung cơ bản như sau: Chương trình học được phân định theo hai phần chính:

- Phần một, mở đầu từ chương 1 đến chương 6, làm sáng tỏ về phân tích hệ thống gồm các khái niệm cốt lõi, cấu trúc hệ thống, nhiệm vụ của hệ thống, các bước phát triển và trạng thái hoạt động của hệ thống.

- Phần hai, bao hàm từ chương 7 đến chương 12, chuyên sâu về thiết kế và triển khai hệ thống, bao gồm: lộ trình phát triển hệ thống, thông số kỹ thuật của hệ thống, những vấn đề nảy sinh trong quá trình thực hiện, phân tích các hỗ trợ phục vụ cho ra quyết định, thủ tục kiểm tra và xác nhận.
Cử nhân ngành Thương mại điện tử (Áp dụng từ Khoá 18 - 2023) Đào tạo nguồn nhân lực có kiến thức và kỹ năng chuyên sâu về Thương mại điện tử nhằm giải quyết các bài toán về kinh doanh - quản lý hiện nay, nghiên cứu và chuyển giao công nghệ tiên tiến trong CNTT vào thương mại điện tử, đặc biệt là hướng vào các ứng dụng nhằm góp phần đẩy mạnh sự nghiệp công nghiệp hóa, hiện đại hóa đất nước.
Cử nhân ngành Công nghệ Thông tin (Áp dụng từ Khoá 18 - 2023) cử nhân liên thông chính quy. Hình thức đào tạo: Chính quy tập trung. Số tín chỉ đào tạo: Tối thiểu 52 tín chỉ (bao gồm cả ngoại ngữ). Thời gian đào tạo: 2 năm (4 học kỳ chính).
Cử nhân ngành Công nghệ Thông tin (Áp dụng từ Khoá 18 - 2023) cử nhân văn bằng đại học thứ 2. Hình thức đào tạo: Chính quy tập trung. Số tín chỉ đào tạo: Tối thiểu 74 tín chỉ (bao gồm cả ngoại ngữ). Thời gian đào tạo: 2.5 năm (5 học kỳ chính).
**Chú trọng vào những chủ đề then chốt, Môn Công nghệ Tường lửa và Bảo vệ Mạng Ngoài vi (NT311) chuyên sâu về:**
- Khái quát về Kiến trúc mạng an toàn
- Nhu cầu cấp thiết của doanh nghiệp về bảo mật thông tin
- Công nghệ Tường lửa và Mạng ngoài vi
- Hệ thống lọc gói tin và Máy chủ Proxy
- Mô hình hệ thống thực tế và giả định trong bảo mật mạng
Môn học Đồ họa máy tính hay còn được biết với mã CS4143, là một chuyên ngành bao phủ các chủ đề sau: lập trình đồ họa tương tác, cấu trúc phần cứng đồ họa, phép biến đổi hình học, tổ chức dữ liệu đồ thị, tổng quan về 3D, biểu diễn hình ảnh 3D, thuật toán xử lý bề mặt và vật ẩn, cùng với các phương pháp tô bóng.
Cử nhân ngành An toàn Thông tin (Áp dụng từ khóa 18 - 2023) Sinh viên tốt nghiệp ngành An toàn thông tin nắm vững kiến thức cơ bản và chuyên sâu về đảm bảo an toàn thông tin cho các hệ thống thông tin, hạ tầng mạng, đáp ứng yêu cầu về nghiên cứu, ứng dụng, có khả năng áp dụng các kiến thức bảo mật vào thiết kế, cài đặt, đánh giá, vận hành hệ thống thông tin. Ngoài ra, chương trình đào tạo cũng tập trung trang bị cho người học các kỹ năng và thái độ đảm bảo sinh viên tốt nghiệp có khả năng làm việc nhóm, phẩm chất chính trị tốt, ý thức tổ chức kỷ luật và có đạo đức nghề nghiệp.
Môn Thiết kế, quản lý và quản trị hệ CSDL (MSIS4013) tập trung vào: - Lý thuyết và thực hành về mô hình dữ liệu và hệ thống CSDL - An ninh dữ liệu, đảm bảo tính toàn vẹn CSDL và quản trị CSDL trong các môi trường phân tán, liên mạng và chia sẻ - Khái niệm CSDL, bao gồm CSDL hướng đối tượng và phát triển CSDL Web - Phân tích, thiết kế và triển khai các hệ thống CSDL sử dụng các công cụ CSDL và ngôn ngữ cấp cao để trích xuất và thao tác dữ liệu

In [9]:
data.keys()

dict_keys(['train', 'validation', 'test'])

In [16]:
len(df)

4230

In [17]:
import pandas as pd 

df = pd.DataFrame(df)

In [18]:
df

                                                context
0     Môn học Kiến trúc hệ thống và Tích hợp hệ thốn...
1     Mã môn học của môn Toán cho Khoa học máy tính ...
2     Môn Thực tập doanh nghiệp mang mã NT115, bao g...
3     Cử nhân ngành Công nghệ Thông tin (Áp dụng từ ...
4     **Đoạn văn được viết lại:**\n\nMôn học có mã N...
...                                                 ...
4225  Với mã học phần NT133, môn An toàn kiến trúc h...
4226  Môn học Cơ chế hoạt động của mã độc có mã môn ...
4227  Môn học Công nghệ thoại IP có mã môn học là NT...
4228  Môn học "Lập trình game trong các thiết bị di ...
4229  Môn Công nghệ phần mềm chuyên sâu được mã hóa ...

[4230 rows x 1 columns]

In [22]:
new_df = df[df.duplicated() == False].reset_index()

In [29]:
new_df.drop(columns=["index"], axis=1,inplace=True)

In [30]:
new_df

                                               context
0    Môn học Kiến trúc hệ thống và Tích hợp hệ thốn...
1    Mã môn học của môn Toán cho Khoa học máy tính ...
2    Môn Thực tập doanh nghiệp mang mã NT115, bao g...
3    Cử nhân ngành Công nghệ Thông tin (Áp dụng từ ...
4    **Đoạn văn được viết lại:**\n\nMôn học có mã N...
..                                                 ...
339  Môn học CS111 về Nguyên lý và phương pháp lập ...
340  Môn học Khoa học Dữ liệu với mã DS201 có trọng...
341  Môn học CE124 là môn học về thiết bị và mạch đ...
342  Môn học CE222 là môn Thiết kế vi mạch số. Tóm ...
343  Môn học Mô hình Đồ thị Xác suất (DS308) cung c...

[344 rows x 1 columns]

In [35]:
new_df.to_csv(r"C:\Users\leduc\OneDrive\Desktop\NLP\UIT-chatbot\uit_course.csv")